version "4.14.0"

#include "zscript/lib/ZJSON/Include.zs"
#include "zscript/lib/debug.zsc"

#include "zscript/GZNovel/Handler/Handler.zsc"
#include "zscript/GZNovel/Handler/_GoNextPage.zsc"
#include "zscript/GZNovel/Handler/_LoadBook.zsc"
#include "zscript/GZNovel/Handler/_LoadCharacter.zsc"
#include "zscript/GZNovel/Handler/_LoadConfig.zsc"
#include "zscript/GZNovel/Characters.zsc"
#include "zscript/GZNovel/Page.zsc"
#include "zscript/GZNovel/Book.zsc"