extend class UZNovelHandler
{
    void LoadBooks(string fileName) 
    {
        // Find file
        int lump = Wads.CheckNumForFullName(fileName);
        if(lump == -1)
        {
            Debug.LogWarning("LoadBooks() : Could not load json named \cf"..fileName);
            return;
        }

        JsonElementOrError data = JSON.parse(Wads.ReadLump(lump),false);
		if(data is "JsonError")
			Debug.Throw("LoadBooks(): "..JsonError(data).what);

        // Deserialize
        JsonObject obj = JsonObject(JsonElement(data));

        JsonElement bookArrElement = obj.get("Books");
        if(!bookArrElement)
        {
            JsonElement misspelledBooks = obj.get("Book"); 
            Debug.Throw("LoadBooks(): Could not find array \cfBooks\c-."..(misspelledBooks ? "\nIntead, \cfBook\c- is found. Did you forget to \cfwrite extra s?\c-" : ""));
        }
        JsonArray bookArr = JsonArray(bookArrElement);

        if(!bookArr) Debug.Throw("LoadBooks(): Element \cfBooks\c- is found but it is not \cfArray\c-, but "..bookArrElement.GetClassName());
        
        for(uint i = 0; i < bookArr.size(); i++)
        {
            Book book = Book.Create();
            JsonObject bookObj = JsonObject(bookArr.get(i));
            
            // Necessary properties
            JsonString nameJson = JsonString(bookObj.get("Name"));
            JsonArray  pagesArr = JsonArray (bookObj.get("Pages"));

            if(!nameJson) Debug.Throw("LoadBooks(): At Book "..(i+1).." : Property \cfName\c- is not present, or type is not \cfstring\c-");
            if(!pagesArr) Debug.Throw("LoadBooks(): At Book "..(i+1).." : Property \cfPages\c- is not present, or type is not \cfarray\c-");
            
            // Check if book with same name had already been loaded.
            if(FindBook(nameJson.s))
            {
                Debug.LogWarning("LoadBooks() : From \cf"..fileName.."\c-, book \cf"..nameJson.s.."\c- is already loaded. Make sure you are not loading the \cfsame book again\c- or check if you have \cfbooks with same name between files!\c-");
                continue;
            }
            
            book.name = nameJson.s;

            // Pages
            Array<Page> pages;
            for(uint j = 0; j < pagesArr.Size(); j++)
            {
                Page page = Page.Create();

                JsonObject pageObj            = JsonObject(pagesArr.Get(j));
                // Properties
                JsonString bgJson             = JsonString(pageObj.get("BG"));
                JsonArray  cgJson             = JsonArray (pageObj.get("CG"));
                JsonString sfxJson            = JsonString(pageObj.get("Sound"));
                JsonString musicJson          = JsonString(pageObj.get("Music"));
                JsonString textJson           = JsonString(pageObj.get("Text"));
                JsonArray  textPivotJson      = JsonArray (pageObj.get("TextPivot"));
                JsonInt    timeJson           = JsonInt   (pageObj.get("Time"));
                JsonArray  charJson           = JsonArray (pageObj.get("Characters"));
                JsonArray  removeJson         = JsonArray (pageObj.get("Remove"));
                JsonArray  highlightJson      = JsonArray (pageObj.get("Highlight"));
                JsonElement ACSJson           = pageObj.get("ACS");
                
                // BG
                if(bgJson)
                {
                    TextureID tex = Texman.CheckForTexture(bgJson.s);
                    if(tex.IsValid() == false) // TODO : Put error texture upon false
                        Debug.LogWarning("LoadBooks(): At Page "..(j+1).."  of Book "..(i+1)..": Property \cfBG\c-'s graphic is not valid. Make sure you input correct directory or the graphic's file is there");
                    page.bg = tex;
                }
                
                // CG
                if(cgJson)
                {  
                    for(int k = 0; k < cgJson.Size(); k++)
                    {
                        CG cg = CG.Create();
                        JsonObject  cgObjJson     = JsonObject(cgJson.Get(k)); 

                        JsonInt     cgIDJson      = JsonInt   (cgObjJson.get("id"));
                        JsonString  graphicJson   = JsonString(cgObjJson.get("Graphic"));
                        JsonArray   posJson       = JsonArray (cgObjJson.get("Pos"));
                        JsonArray   sizeJson      = JsonArray (cgObjJson.get("Size"));
                        JsonArray   cgPivotJson   = JsonArray (cgObjJson.get("Pivot"));
                        JsonInt     cgFadeOutJson = JsonInt   (cgObjJson.get("FadeOut"));
                        JsonInt     cgFadeInJson  = JsonInt   (cgObjJson.get("FadeIn"));

                        TextureID tex = Texman.CheckForTexture((graphicJson == null ? "" : graphicJson.s));
                        if(tex.IsValid() == false)
                            Debug.LogWarning("LoadBooks(): At Page "..(j+1)..": Property \cfCG\c-'s graphic is not valid. Make sure you input correct directory or the graphic's file is there");

                        if(!cgIDJson)  Debug.Throw("LoadBooks(): At Book "..(i+1).." At Page "..(j+1).."At CG "..(k+1).." : Property \cfid\c- is not present, or type is not \cfint\c-");
                        cg.id = cgIDJson.asInt();

                        double posX, posY, sizeX, sizeY;
                        if(posJson && JsonDouble(posJson)) posX = JsonDouble(posJson.Get(0)).asDouble();
                        else                                  posX = 0.5;
                        if(posJson && JsonDouble(posJson.Get(1))) posY = JsonDouble(posJson.Get(1)).asDouble();
                        else                                  posY = 0.5;

                        if(sizeJson && JsonDouble(sizeJson.Get(0))) sizeX = JsonDouble(sizeJson.Get(0)).asDouble();
                        else                                    sizeX = 1.0;
                        if(sizeJson && JsonDouble(sizeJson.Get(1))) sizeY = JsonDouble(sizeJson.Get(1)).asDouble();
                        else                                    sizeY = 1.0;

                        if(!cgPivotJson) cg.pivot = PIVOT_CENTER|PIVOT_MIDDLE;
                        else                   
                        {
                            for(int l = 0; l < cgPivotJson.Size(); l++)
                            {
                                string item = JsonString(cgPivotJson.Get(l)).s;
                                if(item == "Left")   cg.pivot |= PIVOT_LEFT;
                                if(item == "Center") cg.pivot |= PIVOT_CENTER;
                                if(item == "Right")  cg.pivot |= PIVOT_RIGHT;
                                if(item == "Top")    cg.pivot |= PIVOT_TOP;
                                if(item == "Middle") cg.pivot |= PIVOT_MIDDLE;
                                if(item == "Bottom") cg.pivot |= PIVOT_BOTTOM;
                            }
                        }

                        if(cgFadeOutJson) cg.fadeOut = -1.0 / cgFadeOutJson.asDouble(); // is negative in order to decrement by adding (alpha += fadeout)
                        else              cg.fadeOut = 0; // Zero means it will disappear right away.

                        if(cgFadeInJson)  cg.fadeIn = 1.0 / cgFadeInJson.asDouble();
                        else              cg.fadeIn = 1.0;

                        cg.graphic = tex;
                        cg.pos = (posX, posY);
                        cg.size= (sizeX, sizeY);

                        page.cg.Push(cg);
                    }
                }

                if(sfxJson)        page.sound = sfxJson.s;
                if(musicJson)      page.music = musicJson.s;
                if(textJson)       page.text = textJson.s;
                if(timeJson)       page.time = timeJson.asInt();

                if(!textPivotJson) page.textPivot = PIVOT_LEFT|PIVOT_TOP;
                else                   
                {
                    for(int i = 0; i < textPivotJson.Size(); i++)
                    {
                        string item = JsonString(textPivotJson.Get(i)).s;
                        if(item == "Left")   page.textPivot |= PIVOT_LEFT;
                        if(item == "Center") page.textPivot |= PIVOT_CENTER;
                        if(item == "Right")  page.textPivot |= PIVOT_RIGHT;
                        if(item == "Top")    page.textPivot |= PIVOT_TOP;
                        if(item == "Middle") page.textPivot |= PIVOT_MIDDLE;
                        if(item == "Bottom") page.textPivot |= PIVOT_BOTTOM;
                    }
                }
                

                if(removeJson)
                {
                    Array<string> tempRemove;
                    for(uint l = 0; l < removeJson.Size(); l++)
                    {
                        tempRemove.Push(JsonString(removeJson.get(l)).s);
                    }
                    page.remove.Move(tempRemove);
                }

                if(highlightJson)
                {
                    Array<string> tempHighlight;
                    for(uint l = 0; l < highlightJson.Size(); l++)
                    {
                        tempHighlight.Push(JsonString(highlightJson.get(l)).s);
                    }
                    page.highlight.Move(tempHighlight);
                }

                if(charJson)
                {
                    for(uint k = 0; k < charJson.size(); k++)
                    {
                        Directive directive = Directive.Create();

                        JsonObject charObj = JsonObject(charJson.Get(k));
                        if(!charObj)
                            Debug.Throw("LoadBooks(): At Character "..(k+1).." of Page "..(j+1).." : Characters array should not have other than Objects.");
                        
                        // Properties
                        JsonString char_codeNameJson = JsonString(charObj.get("Codename"));
                        JsonString char_nameJson     = JsonString(charObj.get("Name"));
                        JsonString char_graphicJson  = JsonString(charObj.get("Graphic"));
                        JsonInt    char_stateJson    = JsonInt   (charObj.get("State"));
                        JsonDouble char_posJson      = JsonDouble(charObj.get("Pos"));
                        JsonArray  char_sizeJson     = JsonArray (charObj.get("Size"));
                        JsonBool   char_speakerJson  = JsonBool  (charObj.get("IsSpeaker"));

                        if(char_codeNameJson) directive.codeName = char_codeNameJson.s;
                        if(char_nameJson)     directive.name     = char_nameJson.s;
                        if(char_stateJson)    directive.state    = char_stateJson.asInt();
                        if(char_posJson)      directive.pos      = char_posJson.asDouble();
                        if(char_speakerJson)  directive.speaker  = char_speakerJson.b;

                        if(char_graphicJson)
                        {
                            TextureID tex = Texman.CheckForTexture(char_graphicJson.s);
                            if(tex.IsValid() == false)
                                Debug.LogWarning("LoadBooks(): At Character"..(k+1).." of Page "..(j+1)..": Property \cfGraphic\c-'s graphic is not valid. Make sure you input correct directory or the graphic's file is there");
                            directive.graphic = tex;
                        }

                        if(char_sizeJson)
                        {
                            double sizeX = JsonDouble(char_sizeJson.Get(0)).asDouble();
                            double sizeY = JsonDouble(char_sizeJson.Get(1)).asDouble();
                            directive.size = (sizeX, sizeY);
                        }
                        else
                            directive.size = (1.0, 1.0); // Default value for size

                        page.directives.push(directive);
                    }
                }

                // ACS
                if(ACSJson)
                {
                    if(ACSJson is "JsonString")
                    {
                        page.acs.name = JsonString(ACSJson).s;
                    }
                    else if (ACSJson is "JsonNumber")
                    {
                        page.acs.index = JsonNumber(ACSJson).asInt();
                    }
                    else
                    {
                        Debug.LogError("LoadBooks() : At Page "..(j+1).." : ACS is defined but is not string nor int")
                    }
                }

                Debug.LogDebug("LoadBook(): From \cf"..fileName.."\c-\n   Loaded Page "..(j+1)..":\n     "..page.Serialize());
                pages.push(page);
            }

            book.pages.Move(pages);

            Debug.LogDebug("LoadBook(): From \cf"..fileName.."\c-\n   Loaded book:\n     "..book.name);

            books.Push(book);
        }
    }
}