struct Stage
{
    Array<Character> characters;
    Array<CG>        cg;
    TextureID        bg;
    int              autoReadtimer;

    // Volatile stage properties
    // volatile means it will be re-initialized on GoNextPage()

        // Speakers.
        string  speakers; 
        // How many characters of texts will be shown per tic?
        double  textTimerCoefficient; 
        string  text; 
        int     textLines; 
        double  textTimer; 
        Vector2 textPos; 

        string prevMusic;
}

Class UZNovelHandler : EventHandler
{
    public  Stage            stage;
    public  Book             curBook;
    public  int              curPage; // if -1, means it is not playing books.
    private GZNConfig        config;

    public  Array<Character> characters;
    public  Array<Book>      books;

    private Book             _ErrorBook;

    public  CVar             autoReadCvar;

    override void OnRegister()
    {
        autoReadCvar = CVar.GetCVar("cl_uznovel_autoread", players[ConsolePlayer]);
        LoadConfig();
    }

    // Since UZNovel is dynamic EventHandler, it is wise to load these on new game.
    override void NewGame()
    {
        Debug.LogDebug("GZNOVEL : Initializing");
        
        LoadCharacters("/books/errorbook.json");
        LoadBooks("/books/errorbook.json");
        curPage = -1;
    }

    override void WorldUnloaded (WorldEvent e)
    {
        //if(IsInBook())
        //    EndBook();
    }

    static UZNovelHandler Get()
    {
        return UZNovelHandler(EventHandler.Find('UZNovelHandler'));
    }
    
    // Finds book with given name
    Book FindBook(string what)
    {
        for(int i = 0; i < books.Size(); i++)
        {
            if(books[i].name == what)
                return books[i];
        }
        return null;
    }

    // Starts reading book with given name
    void StartBook(string what) 
    {
        Book bookToRead = FindBook(what);
        if(!bookToRead)
        {
            Debug.LogWarning("StartBook() : Could not find book \cf"..what.."\c-. Loading Error Book instead.");
            bookToRead = FindBook("__ERROR__BOOK__");
        }
        curBook = bookToRead;
        level.SetFrozen(true); // TODO : make this variable with Page block
        S_PauseSound(false, true);
        stage.prevMusic = level.music;
        // Starts from beginning of the book
        GoNextPage(0); 
    }

    // Finish reading book regardless which page it is in
    void EndBook() 
    {
        // Clear book information
        curBook = null;
        curPage = -1;

        // Clear stage properties
        stage.characters.Clear();
        stage.speakers = "";
        stage.textTimerCoefficient = 0.0;
        stage.text = "";
        stage.textLines = 0;
        stage.textTimer = 0;
        stage.cg.Clear();

        // Resume sound, musics and shit
        S_ResumeSound(false);
        S_ChangeMusic(stage.prevMusic);
        
        // Cuts the sound
        if(players[0].mo) players[0].mo.A_StartSound("", 1, CHANF_LOOP);
        level.SetFrozen(false);
    }

    // Check if a book is being played
    clearscope bool IsInBook()
    {
        if(curBook != null && curPage >= 0)
            return true;
        return false;
    }

    clearscope bool TextReachedEnd()
    {
        if(!IsInBook())
            return false;
        return (int(stage.textTimer) >= stage.text.Length());
    }

    // Finds a character by codename
    Character FindCharacter(string codeName)
    {
        for(int i = 0; i < characters.Size(); i++) // I REALLY need to study some algorhithm bullshits to minimize such simple for loop parsing.
        {
            if(characters[i].codeName == codeName)
                return characters[i];
        }
        return null;
    }

    override void WorldTick()
    {
        if(IsInBook())
        {
            //
            // Autoread
            //

            // if text is being all displayed
            if(TextReachedEnd())
            {
                if(autoReadCvar)
                {
                    if(autoReadCvar.GetBool())
                    {
                        stage.autoReadtimer++;

                        if(stage.autoReadtimer >= config.autoReadGap)
                        {
                            stage.autoReadtimer = 0;
                            GoNextPage();
                        }
                    }
                }
                return;
            }
                
            if(!TextReachedEnd())
                stage.textTimer += stage.textTimerCoefficient;

            //
            // CG
            //

            for(int i = 0; i < stage.cg.Size(); i++)
            {
                CG curCG = stage.cg[i];
                // if curCG has to fadeout
                if(curCG.fadeOut < 0.0)
                {
                    if(curCG.alpha <= 0.0)
                    {
                        Debug.LogDebug("CG "..curCG.id.." is gone");
                        stage.cg.Delete(i);
                        continue;
                    }
                    curCG.alpha += curCG.fadeOut;
                }
                else // fadein (or not fading at all)
                {
                    curCG.alpha += curCG.fadeIn;

                    if(curCg.alpha > 1.0)
                        curCg.alpha = 1.0;
                }               
            }
        }
    }

    override bool InputProcess (InputEvent e)
    {
        if(IsInBook())
        {
            if(e.type == e.Type_KeyDown)
            {
                // if desired key to skip had been pressed
                if(bindings.GetBinding(e.KeyScan) == "+attack")
                {
                    Debug.LogDebug("InputProcess.GoNextPage : Proceeding to next page");

                    // End fading sequence of cg
                    for(int i = 0; i < stage.cg.Size(); i++)
                    {
                        stage.cg[i].alpha = 1.0;
                        if(stage.cg[i].fadeOut < 0.0)
                            stage.cg[i].alpha = 0.0;
                    }

                    if(!TextReachedEnd())
                        stage.textTimer = stage.text.Length(); // Will skip to the end of the text
                    else
                        EventHandler.SendNetworkEvent("GoNextPage");
                }
            }
        }
        return false;
    }

    override void NetworkProcess(ConsoleEvent e)
    {
        // Cheat codes and shits

        Array<String> args;
        e.name.split(args, "|");

        if(args[0] == "GoNextPage") // Seems dangerous if 'mistakenly' called via netevent.
            GoNextPage();

        if(args[0] == "ShowBooks")
        {
            console.printf("UZNovel : Currently loaded books\n    ");
            foreach(a : books)
            {
                console.printf(a.name.."\n    ");
            }
            if(curBook)
                console.printf("Currently Playing Book : "..curBook.name);
        }

        if(args[0] == "SerializeStage")
        {
            console.printf("UZNovel : Printing current stage info..");
                console.printf("\n    IsInBook() : "..IsInBook());
                console.printf("\n    curPage : "..curPage);
                console.printf("\n    characters.size : "..stage.characters.size());
                console.printf("\n    cg.size : "..stage.cg.size());
                console.printf("\n    bg : "..Texman.GetName(stage.bg));
                console.printf("\n    speakers : "..stage.speakers);
                console.printf("\n    textTimerCoefficient : "..stage.textTimerCoefficient);
                console.printf("\n    textLines : "..stage.textLines);
                console.printf("\n    textTimer : "..stage.textTimer.."(Text length : "..stage.text.Length()..")");
                console.printf("\n    textPos : "..stage.textPos);
                console.printf("\n    autoReadtimer : "..stage.autoReadtimer);
        }
    }

    override void RenderOverlay (RenderEvent e)
    {
        if(IsInBook())
        {
            if(!config.isSetup)
            {
                Debug.LogWarning("UZNovel is not setup properly! Please check your \cfUZNINFO.json\c- again!");
                return;
            }

            Page curRealPage = curBook.pages[curPage];

            // BG
            GZN_DrawImage(stage.bg, (0.0, 0.0));

            // CG
            for(int i = 0; i < stage.cg.Size(); i++)
            {
                GZN_DrawImage(stage.cg[i].graphic, stage.cg[i].pos, pivot:stage.cg[i].pivot, size:stage.cg[i].size, alpha:stage.cg[i].alpha);
            }

            // Characters
            for(int i = 0; i < stage.characters.Size(); i++)
            {
                Character curCharacter = stage.characters[i];
                GZN_DrawImage(curCharacter.curGraphic, (curCharacter.pos, 1.0), highlight : curCharacter.IsHighlight, size:curCharacter.size);
            }

            if(stage.text != "") 
            {
                // Dialogue box
                GZN_DrawImage(config.dialogueBG, (0.5, 1.0));

                // Speaker
                GZN_DrawText(stage.speakers, config.speakerPos, pivot:config.speakerPivot, size:(config.speakerTextSize, config.speakerTextSize));

                GZN_DrawText(stage.text.Left(int(stage.textTimer)), stage.textPos, pivot:curRealPage.textPivot, line:stage.textLines, size:(config.dialogueTextSize, config.dialogueTextSize));
            }
        }
    }
}