#include "./Common/pool.zsc"

#include "./lib/ZJSON/Include.zs"
#include "./lib/debug.zsc"

#include "./Elements/Characters.zsc"
#include "./Elements/Page.zsc"
#include "./Elements/Book.zsc"

#include "./Handler/Handler.zsc"
#include "./Handler/_GoNextPage.zsc"
#include "./Handler/_LoadBook.zsc"
#include "./Handler/_LoadCharacter.zsc"
#include "./Handler/_LoadConfig.zsc"
#include "./Handler/_Draws.zsc"
#include "./Handler/_Unload.zsc"

#include "./UZNovel.zsc"